export const TracksActions = {
    LOAD_TRACKS: 'LOAD_TRACKS',
    ADD_TRACK: 'ADD_TRACK',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    SET_PLAYING_STATUS: 'SET_PLAYING_STATUS',
    SET_PLAYER: 'SET_PLAYER',
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE'
};

export const AlbumsActions = {
    ALBUMS_ARE_STORING: 'ALBUMS_ARE_STORING'
};

export const PhotosActions = {
    PHOTOS_ARE_STORING: 'PHOTOS_ARE_STORING',
    ADD_PHOTOS_TO_ALBUM: 'ADD_PHOTOS_TO_ALBUM'
};

export const FetchAlbumsActions = {
    START: 'FETCH_ALBUMS_START',
    SUCCESS: 'FETCH_ALBUMS_SUCCESS',
    ERROR: 'FETCH_ALBUMS_ERROR'
};

export const FetchPhotosActions = {
    START: 'FETCH_PHOTOS_START',
    SUCCESS: 'FETCH_PHOTOS_SUCCESS',
    ERROR: 'FETCH_PHOTOS_ERROR'
};