export const TracksActions = {
    LOAD_TRACKS: 'LOAD_TRACKS',
    ADD_TRACK: 'ADD_TRACK',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    SET_PLAYING_STATUS: 'SET_PLAYING_STATUS',
    SET_PLAYER: 'SET_PLAYER',
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE'
};

export const AlbumsActions = {
    ALBUMS_ARE_LOADING: 'ALBUMS_ARE_LOADING',
    FETCH_ALBUMS_HAS_ERROR: 'FETCH_ALBUMS_HAS_ERROR',
    FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',
};

export const PhotosActions = {
    PHOTOS_ARE_LOADING: 'PHOTOS_ARE_LOADING',
    FETCH_PHOTOS_HAS_ERROR: 'FETCH_PHOTOS_HAS_ERROR',
    FETCH_PHOTOS_SUCCESS: 'FETCH_PHOTOS_SUCCESS',
    ADD_PHOTOS_TO_ALBUM: 'ADD_PHOTOS_TO_ALBUM'
};