export const ADD_TRACK = 'ADD_TRACK';
export const SET_CURRENT_TRACK_ID = 'SET_CURRENT_TRACK_ID';
export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS';
export const SHOW_FAVORITES_TRACKS = 'SHOW_FAVORITES_TRACKS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const PLAYING_STATUS_PLAYING = 'PLAYING';
export const PLAYING_STATUS_STOPPED = 'STOPPED';
export const PLAYING_STATUS_PAUSED = 'PAUSED';

