export const ADD_TRACK = 'ADD_TRACK';
export const SET_CURRENT_TRACK_ID = 'SET_CURRENT_TRACK_ID';
export const SHOW_FAVORITES_TRACKS = 'SHOW_FAVORITES_TRACKS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
