export const LOAD_TRACKS = 'LOAD_TRACKS';
export const ADD_TRACK = 'ADD_TRACK';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS';
export const SET_PLAYER = 'SET_PLAYER';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const PLAYING_STATUS_PLAYING = 'PLAYING';
export const PLAYING_STATUS_STOPPED = 'STOPPED';
export const PLAYING_STATUS_PAUSED = 'PAUSED';

export const PLAYER_FIRST = 'playerFirst';
export const PLAYER_SECOND = 'playerSecond';

export const SELECT_ALBUM = 'SELECT_ALBUM';
export const SELECT_PHOTO = 'SELECT_PHOTO';

export const ALBUMS_ARE_LOADING = 'ALBUMS_ARE_LOADING';
export const FETCH_ALBUMS_HAS_ERROR = 'FETCH_ALBUMS_HAS_ERROR';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
// export const PHOTOS_ARE_LOADING = 'PHOTOS_ARE_LOADING';

